---
name: eslint
on:
  push:
    branches:
      - main
      - develop

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-check
          level: error
          workdir: lambda/
